import React, { useEffect, useState } from 'react';
import { DataStore } from 'aws-amplify';
import { Task } from './models'; // Import the Task model generated by Amplify




function Home() {
  
  const [tasks, setTasks] = useState([]);

  useEffect(() => {
    const fetchTasks = async () => {
      try {
        const tasks = await DataStore.query(Task);
        setTasks(tasks);
        console.log('Tasks retrieved successfully!', tasks);
      } catch (error) {
        console.log('Error retrieving tasks', error);
      }
    };

    fetchTasks();
  }, []);

  const createTask = async () => {
    try {
      const newTask = await DataStore.save(
        new Task({
          title: 'New Task',
          description: 'This is a new task',
          status: 'ACTIVE'
        })
      );
      setTasks((prevTasks) => [...prevTasks, newTask]);
      console.log('Task created successfully!', newTask);
    } catch (error) {
      console.log('Error creating task', error);
    }
  };

  return (
    <div className="App">
      
      <header className="App-header">

        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a className="App-link" href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
          Learn React
        </a>
        <div>
          <h2>Tasks:</h2>
          <ul>
            {tasks.map((task) => (
              <li key={task.id}>{task.title}</li>
            ))}
          </ul>
        </div>
        <button onClick={createTask}>Create Task</button>
      </header>
    </div>
  );
}

export default Home;